# Form implementation generated from reading ui file './ui/login_register.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_login_register(object):
    def setupUi(self, dl_login_register):
        dl_login_register.setObjectName("dl_login_register")
        dl_login_register.resize(329, 158)
        self.verticalLayout = QtWidgets.QVBoxLayout(dl_login_register)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=dl_login_register)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_username = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_username.setObjectName("lbl_username")
        self.gridLayout.addWidget(self.lbl_username, 0, 0, 1, 1)
        self.le_username = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_username.setObjectName("le_username")
        self.gridLayout.addWidget(self.le_username, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.le_password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.le_password.setObjectName("le_password")
        self.gridLayout.addWidget(self.le_password, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_close = QtWidgets.QPushButton(parent=dl_login_register)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_register = QtWidgets.QPushButton(parent=dl_login_register)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout.addWidget(self.btn_register)
        self.btn_login = QtWidgets.QPushButton(parent=dl_login_register)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dl_login_register)
        QtCore.QMetaObject.connectSlotsByName(dl_login_register)

    def retranslateUi(self, dl_login_register):
        _translate = QtCore.QCoreApplication.translate
        dl_login_register.setWindowTitle(_translate("dl_login_register", "Login / Register"))
        self.groupBox.setTitle(_translate("dl_login_register", "User Infomation"))
        self.lbl_username.setText(_translate("dl_login_register", "Username"))
        self.lbl_password.setText(_translate("dl_login_register", "Password"))
        self.btn_close.setText(_translate("dl_login_register", "Close"))
        self.btn_register.setText(_translate("dl_login_register", "Register"))
        self.btn_login.setText(_translate("dl_login_register", "Login"))
