# Form implementation generated from reading ui file 'ui/task4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task4(object):
    def setupUi(self, dl_task4):
        dl_task4.setObjectName("dl_task4")
        dl_task4.resize(801, 420)
        dl_task4.setMinimumSize(QtCore.QSize(801, 420))
        dl_task4.setMaximumSize(QtCore.QSize(801, 420))
        self.horizontalLayout = QtWidgets.QHBoxLayout(dl_task4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_export.setObjectName("btn_export")
        self.verticalLayout.addWidget(self.btn_export)
        self.btn_load = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout.addWidget(self.btn_load)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tb_info = QtWidgets.QTableWidget(parent=dl_task4)
        self.tb_info.setObjectName("tb_info")
        self.tb_info.setColumnCount(6)
        self.tb_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_info.setHorizontalHeaderItem(5, item)
        self.horizontalLayout.addWidget(self.tb_info)

        self.retranslateUi(dl_task4)
        QtCore.QMetaObject.connectSlotsByName(dl_task4)

    def retranslateUi(self, dl_task4):
        _translate = QtCore.QCoreApplication.translate
        dl_task4.setWindowTitle(_translate("dl_task4", "Student Information Management"))
        self.btn_add.setText(_translate("dl_task4", "Add"))
        self.btn_export.setText(_translate("dl_task4", "Export to Excel file"))
        self.btn_load.setText(_translate("dl_task4", "Load from Excel file"))
        item = self.tb_info.horizontalHeaderItem(0)
        item.setText(_translate("dl_task4", "Student ID"))
        item = self.tb_info.horizontalHeaderItem(1)
        item.setText(_translate("dl_task4", "Name"))
        item = self.tb_info.horizontalHeaderItem(2)
        item.setText(_translate("dl_task4", "Phone"))
        item = self.tb_info.horizontalHeaderItem(3)
        item.setText(_translate("dl_task4", "Math"))
        item = self.tb_info.horizontalHeaderItem(4)
        item.setText(_translate("dl_task4", "Literature"))
        item = self.tb_info.horizontalHeaderItem(5)
        item.setText(_translate("dl_task4", "GPA"))
