# Form implementation generated from reading ui file './tasks/task3/ui/task3.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task3(object):
    def setupUi(self, dl_task3):
        dl_task3.setObjectName("dl_task3")
        dl_task3.resize(518, 556)
        dl_task3.setMinimumSize(QtCore.QSize(518, 556))
        dl_task3.setMaximumSize(QtCore.QSize(518, 556))
        self.verticalLayout = QtWidgets.QVBoxLayout(dl_task3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_file_name = QtWidgets.QLineEdit(parent=dl_task3)
        self.lbl_file_name.setReadOnly(True)
        self.lbl_file_name.setObjectName("lbl_file_name")
        self.horizontalLayout.addWidget(self.lbl_file_name)
        self.btn_get = QtWidgets.QPushButton(parent=dl_task3)
        self.btn_get.setObjectName("btn_get")
        self.horizontalLayout.addWidget(self.btn_get)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_image = QtWidgets.QLabel(parent=dl_task3)
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.verticalLayout.addWidget(self.lbl_image)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(dl_task3)
        QtCore.QMetaObject.connectSlotsByName(dl_task3)

    def retranslateUi(self, dl_task3):
        _translate = QtCore.QCoreApplication.translate
        dl_task3.setWindowTitle(_translate("dl_task3", "Random Catto Image"))
        self.lbl_file_name.setPlaceholderText(_translate("dl_task3", "File name"))
        self.btn_get.setText(_translate("dl_task3", "Get"))
