# Form implementation generated from reading ui file './ui/mail_content.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_mail_content(object):
    def setupUi(self, dlg_mail_content):
        dlg_mail_content.setObjectName("dlg_mail_content")
        dlg_mail_content.resize(715, 524)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlg_mail_content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.te_content = QtWidgets.QTextEdit(parent=dlg_mail_content)
        self.te_content.setReadOnly(True)
        self.te_content.setObjectName("te_content")
        self.horizontalLayout.addWidget(self.te_content)

        self.retranslateUi(dlg_mail_content)
        QtCore.QMetaObject.connectSlotsByName(dlg_mail_content)

    def retranslateUi(self, dlg_mail_content):
        _translate = QtCore.QCoreApplication.translate
        dlg_mail_content.setWindowTitle(_translate("dlg_mail_content", "Mail Content"))
