# Form implementation generated from reading ui file './tasks/task1/ui/task1.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task1(object):
    def setupUi(self, dl_task1):
        dl_task1.setObjectName("dl_task1")
        dl_task1.resize(973, 649)
        dl_task1.setMinimumSize(QtCore.QSize(973, 649))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(dl_task1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_url = QtWidgets.QLineEdit(parent=dl_task1)
        self.le_url.setObjectName("le_url")
        self.verticalLayout.addWidget(self.le_url)
        self.te_source = QtWidgets.QTextEdit(parent=dl_task1)
        self.te_source.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.te_source.setObjectName("te_source")
        self.verticalLayout.addWidget(self.te_source)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_download = QtWidgets.QPushButton(parent=dl_task1)
        self.btn_download.setObjectName("btn_download")
        self.horizontalLayout.addWidget(self.btn_download)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tw_headers = QtWidgets.QTableWidget(parent=dl_task1)
        self.tw_headers.setAutoFillBackground(False)
        self.tw_headers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tw_headers.setObjectName("tw_headers")
        self.tw_headers.setColumnCount(2)
        self.tw_headers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_headers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_headers.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tw_headers)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)

        self.retranslateUi(dl_task1)
        QtCore.QMetaObject.connectSlotsByName(dl_task1)

    def retranslateUi(self, dl_task1):
        _translate = QtCore.QCoreApplication.translate
        dl_task1.setWindowTitle(_translate("dl_task1", "View source & headers"))
        self.btn_download.setText(_translate("dl_task1", "Download"))
        item = self.tw_headers.horizontalHeaderItem(0)
        item.setText(_translate("dl_task1", "Header"))
        item = self.tw_headers.horizontalHeaderItem(1)
        item.setText(_translate("dl_task1", "Value"))
