# Form implementation generated from reading ui file './tasks/task2/ui/task2.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task2(object):
    def setupUi(self, dl_task2):
        dl_task2.setObjectName("dl_task2")
        dl_task2.resize(980, 647)
        self.verticalLayout = QtWidgets.QVBoxLayout(dl_task2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_url = QtWidgets.QLineEdit(parent=dl_task2)
        self.le_url.setObjectName("le_url")
        self.horizontalLayout.addWidget(self.le_url)
        self.btn_view_source = QtWidgets.QPushButton(parent=dl_task2)
        self.btn_view_source.setAutoDefault(False)
        self.btn_view_source.setObjectName("btn_view_source")
        self.horizontalLayout.addWidget(self.btn_view_source)
        self.cb_user_agent = QtWidgets.QComboBox(parent=dl_task2)
        self.cb_user_agent.setCurrentText("")
        self.cb_user_agent.setObjectName("cb_user_agent")
        self.horizontalLayout.addWidget(self.cb_user_agent)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.web_view = QtWebEngineWidgets.QWebEngineView(parent=dl_task2)
        self.web_view.setUrl(QtCore.QUrl("about:blank"))
        self.web_view.setObjectName("web_view")
        self.verticalLayout.addWidget(self.web_view)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(dl_task2)
        QtCore.QMetaObject.connectSlotsByName(dl_task2)

    def retranslateUi(self, dl_task2):
        _translate = QtCore.QCoreApplication.translate
        dl_task2.setWindowTitle(_translate("dl_task2", "Web View"))
        self.btn_view_source.setText(_translate("dl_task2", "View Source"))
from PyQt6 import QtWebEngineWidgets
