# Form implementation generated from reading ui file 'ui/task1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task1(object):
    def setupUi(self, dl_task1):
        dl_task1.setObjectName("dl_task1")
        dl_task1.resize(973, 649)
        dl_task1.setMinimumSize(QtCore.QSize(973, 649))
        self.verticalLayout = QtWidgets.QVBoxLayout(dl_task1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.te_content = QtWidgets.QTextEdit(parent=dl_task1)
        self.te_content.setObjectName("te_content")
        self.verticalLayout.addWidget(self.te_content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_to_upper = QtWidgets.QPushButton(parent=dl_task1)
        self.btn_to_upper.setObjectName("btn_to_upper")
        self.horizontalLayout.addWidget(self.btn_to_upper)
        self.btn_to_lower = QtWidgets.QPushButton(parent=dl_task1)
        self.btn_to_lower.setObjectName("btn_to_lower")
        self.horizontalLayout.addWidget(self.btn_to_lower)
        self.btn_read = QtWidgets.QPushButton(parent=dl_task1)
        self.btn_read.setObjectName("btn_read")
        self.horizontalLayout.addWidget(self.btn_read)
        self.btn_write = QtWidgets.QPushButton(parent=dl_task1)
        self.btn_write.setObjectName("btn_write")
        self.horizontalLayout.addWidget(self.btn_write)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dl_task1)
        QtCore.QMetaObject.connectSlotsByName(dl_task1)

    def retranslateUi(self, dl_task1):
        _translate = QtCore.QCoreApplication.translate
        dl_task1.setWindowTitle(_translate("dl_task1", "Read & Write"))
        self.btn_to_upper.setText(_translate("dl_task1", "To Upper"))
        self.btn_to_lower.setText(_translate("dl_task1", "To Lower"))
        self.btn_read.setText(_translate("dl_task1", "Read File"))
        self.btn_write.setText(_translate("dl_task1", "Write File"))
