# Form implementation generated from reading ui file './ui/menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(300, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(menu.sizePolicy().hasHeightForWidth())
        menu.setSizePolicy(sizePolicy)
        menu.setMinimumSize(QtCore.QSize(300, 200))
        menu.setMaximumSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(parent=menu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_task4 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_task4.sizePolicy().hasHeightForWidth())
        self.btn_task4.setSizePolicy(sizePolicy)
        self.btn_task4.setObjectName("btn_task4")
        self.gridLayout_2.addWidget(self.btn_task4, 1, 1, 1, 1)
        self.btn_task2 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_task2.sizePolicy().hasHeightForWidth())
        self.btn_task2.setSizePolicy(sizePolicy)
        self.btn_task2.setObjectName("btn_task2")
        self.gridLayout_2.addWidget(self.btn_task2, 0, 1, 1, 1)
        self.btn_task3 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_task3.sizePolicy().hasHeightForWidth())
        self.btn_task3.setSizePolicy(sizePolicy)
        self.btn_task3.setObjectName("btn_task3")
        self.gridLayout_2.addWidget(self.btn_task3, 1, 0, 1, 1)
        self.btn_task1 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_task1.sizePolicy().hasHeightForWidth())
        self.btn_task1.setSizePolicy(sizePolicy)
        self.btn_task1.setObjectName("btn_task1")
        self.gridLayout_2.addWidget(self.btn_task1, 0, 0, 1, 1)
        menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Menu"))
        self.btn_task4.setText(_translate("menu", "Task 4"))
        self.btn_task2.setText(_translate("menu", "Task 2"))
        self.btn_task3.setText(_translate("menu", "Task 3"))
        self.btn_task1.setText(_translate("menu", "Task 1"))
