# Form implementation generated from reading ui file './tasks/task4/ui/task4.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_task4(object):
    def setupUi(self, dl_task4):
        dl_task4.setObjectName("dl_task4")
        dl_task4.resize(980, 647)
        self.verticalLayout = QtWidgets.QVBoxLayout(dl_task4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_back.setText("")
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.btn_back.setIcon(icon)
        self.btn_back.setAutoDefault(False)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_forward = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_forward.setText("")
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btn_forward.setIcon(icon)
        self.btn_forward.setAutoDefault(False)
        self.btn_forward.setObjectName("btn_forward")
        self.horizontalLayout.addWidget(self.btn_forward)
        self.btn_reload = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_reload.setText("")
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.btn_reload.setIcon(icon)
        self.btn_reload.setAutoDefault(False)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.le_url = QtWidgets.QLineEdit(parent=dl_task4)
        self.le_url.setObjectName("le_url")
        self.horizontalLayout.addWidget(self.le_url)
        self.btn_save_page = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_save_page.setAutoDefault(False)
        self.btn_save_page.setObjectName("btn_save_page")
        self.horizontalLayout.addWidget(self.btn_save_page)
        self.btn_view_source = QtWidgets.QPushButton(parent=dl_task4)
        self.btn_view_source.setAutoDefault(False)
        self.btn_view_source.setObjectName("btn_view_source")
        self.horizontalLayout.addWidget(self.btn_view_source)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.browser = QtWebEngineWidgets.QWebEngineView(parent=dl_task4)
        self.browser.setUrl(QtCore.QUrl("about:blank"))
        self.browser.setObjectName("browser")
        self.verticalLayout.addWidget(self.browser)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(dl_task4)
        QtCore.QMetaObject.connectSlotsByName(dl_task4)

    def retranslateUi(self, dl_task4):
        _translate = QtCore.QCoreApplication.translate
        dl_task4.setWindowTitle(_translate("dl_task4", "Web Browser"))
        self.btn_save_page.setText(_translate("dl_task4", "Save Page"))
        self.btn_view_source.setText(_translate("dl_task4", "View Source"))
from PyQt6 import QtWebEngineWidgets
