# Form implementation generated from reading ui file './tasks/task4/ui/view_source.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_view_souce(object):
    def setupUi(self, dl_view_souce):
        dl_view_souce.setObjectName("dl_view_souce")
        dl_view_souce.resize(959, 562)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dl_view_souce)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pte_source = QtWidgets.QPlainTextEdit(parent=dl_view_souce)
        self.pte_source.setReadOnly(True)
        self.pte_source.setObjectName("pte_source")
        self.horizontalLayout.addWidget(self.pte_source)
        self.tab_headers = QtWidgets.QTabWidget(parent=dl_view_souce)
        self.tab_headers.setEnabled(True)
        self.tab_headers.setObjectName("tab_headers")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_request_headers = QtWidgets.QTableWidget(parent=self.tab)
        self.table_request_headers.setObjectName("table_request_headers")
        self.table_request_headers.setColumnCount(2)
        self.table_request_headers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_request_headers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_request_headers.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.table_request_headers)
        self.tab_headers.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_response_headers = QtWidgets.QTableWidget(parent=self.tab_2)
        self.table_response_headers.setObjectName("table_response_headers")
        self.table_response_headers.setColumnCount(2)
        self.table_response_headers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_response_headers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_response_headers.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.table_response_headers)
        self.tab_headers.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tab_headers)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(dl_view_souce)
        self.tab_headers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dl_view_souce)

    def retranslateUi(self, dl_view_souce):
        _translate = QtCore.QCoreApplication.translate
        dl_view_souce.setWindowTitle(_translate("dl_view_souce", "View Source"))
        item = self.table_request_headers.horizontalHeaderItem(0)
        item.setText(_translate("dl_view_souce", "Header"))
        item = self.table_request_headers.horizontalHeaderItem(1)
        item.setText(_translate("dl_view_souce", "Value"))
        self.tab_headers.setTabText(self.tab_headers.indexOf(self.tab), _translate("dl_view_souce", "Request"))
        item = self.table_response_headers.horizontalHeaderItem(0)
        item.setText(_translate("dl_view_souce", "Header"))
        item = self.table_response_headers.horizontalHeaderItem(1)
        item.setText(_translate("dl_view_souce", "Value"))
        self.tab_headers.setTabText(self.tab_headers.indexOf(self.tab_2), _translate("dl_view_souce", "Response"))
